const THREAD_STORAGE_KEY = "reign-gauntlet-preview-codex-thread-v1";

export function buildCodexTurnPrompt(userText, context) {
  return [
    "The user is editing a Bannerlord Reign interface in the Gauntlet XML Previewer.",
    "Requested change:",
    String(userText || "").trim(),
    "",
    "Current preview context (generated by the previewer):",
    JSON.stringify(context || {}, null, 2),
    "",
    "Implement this request in the workspace. Do not install or deploy it. If the selected child stretches to its parent or is clipped, adjust the correct parent/layout contract and explain that choice."
  ].join("\n");
}

export class CodexPreviewChat {
  constructor({ getContext, onTurnComplete }) {
    this.getContext = getContext;
    this.onTurnComplete = onTurnComplete;
    this.elements = collectElements();
    this.socket = null;
    this.workspaceRoot = "";
    this.threadId = "";
    this.turnId = "";
    this.requestId = 0;
    this.pending = new Map();
    this.activeAssistantMessage = null;
    this.connected = false;
    this.busy = false;
    this.bind();
  }

  async start() {
    this.setStatus("Finding the local Codex editing service…");
    try {
      const response = await fetch("api/preview-environment", { cache: "no-store" });
      const environment = await response.json();
      if (!response.ok) throw new Error(environment.error || `${response.status} ${response.statusText}`);
      if (!environment.codex?.available || !environment.codex.endpoint) {
        throw new Error(environment.codex?.error || "The previewer-owned Codex App Server is unavailable.");
      }
      this.workspaceRoot = environment.workspaceRoot;
      await this.connect(environment.codex.endpoint);
      this.connected = true;
      this.updateControls();
      this.setStatus(this.threadId ? `Ready · task ${shortId(this.threadId)}` : "Ready", "ok");
    } catch (error) {
      this.connected = false;
      this.updateControls();
      this.setStatus(`Unavailable · ${error.message}`, "bad");
      this.appendMessage("system", `Codex chat could not start: ${error.message}`);
    }
  }

  disableForEvidence() {
    this.connected = false;
    this.busy = false;
    this.updateControls();
    this.setStatus("Disabled for provider-free render evidence");
    this.appendMessage("system", "Codex connectivity is intentionally disabled for this automated render. Ordinary previewer sessions keep the editing chat enabled.");
  }

  bind() {
    this.elements.send.addEventListener("click", () => this.send());
    this.elements.prompt.addEventListener("keydown", (event) => {
      if (event.key === "Enter" && !event.shiftKey) {
        event.preventDefault();
        void this.send();
      }
    });
    this.elements.prompt.addEventListener("input", () => this.updateControls());
  }

  async connect(endpoint) {
    this.socket = new WebSocket(endpoint);
    await new Promise((resolve, reject) => {
      const timeout = window.setTimeout(() => reject(new Error("Codex connection timed out.")), 5000);
      this.socket.addEventListener("open", () => { window.clearTimeout(timeout); resolve(); }, { once: true });
      this.socket.addEventListener("error", () => { window.clearTimeout(timeout); reject(new Error("Codex WebSocket connection failed.")); }, { once: true });
    });
    this.socket.addEventListener("message", (event) => this.handleMessage(event));
    this.socket.addEventListener("close", () => {
      this.connected = false;
      this.busy = false;
      this.updateControls();
      this.setStatus("Disconnected; restart the preview server to reconnect.", "bad");
    });
    await this.request("initialize", {
      clientInfo: { name: "reign_gauntlet_xml_previewer", title: "Reign Gauntlet XML Previewer", version: "1.0.0" },
      capabilities: { experimentalApi: true }
    });
    this.notify("initialized", {});
    await this.openThread();
  }

  async openThread() {
    const stored = safeStorageGet(THREAD_STORAGE_KEY);
    if (stored) {
      try {
        const response = await this.request("thread/resume", { threadId: stored });
        this.threadId = response.thread?.id || stored;
        this.appendMessage("system", `Resumed the previewer editing task ${shortId(this.threadId)}.`);
        return;
      } catch {
        safeStorageRemove(THREAD_STORAGE_KEY);
      }
    }

    const response = await this.request("thread/start", {
      cwd: this.workspaceRoot,
      runtimeWorkspaceRoots: [this.workspaceRoot],
      sandbox: "workspace-write",
      approvalPolicy: "never",
      historyMode: "paginated",
      ephemeral: false,
      threadSource: "reign_xml_previewer",
      personality: "pragmatic",
      baseInstructions: "You are the dedicated Codex editing task embedded in the Bannerlord Reign Gauntlet XML Previewer. Work only in the supplied Reign workspace. Follow every AGENTS.md instruction, preserve unrelated dirty-worktree changes, use the Reign MCP validation plan before code edits, use apply_patch for source edits, and never deploy, install files into Bannerlord, start Bannerlord, or mutate a campaign. The human will use the previewer's separately guarded install control after reviewing changes.",
      developerInstructions: "Treat the current interface, selected-widget token, XML path, bindings, geometry, diagnostics, and pending edits in each prompt as authoritative editing context. Inspect the actual XML and relevant renderer/source contracts before changing them. Make the requested change in the workspace, keep it minimal, report exact files changed and verification performed, and call out when a request requires a parent widget or layout-policy change rather than a child text offset."
    });
    this.threadId = response.thread?.id || "";
    if (!this.threadId) throw new Error("Codex did not return an editing task id.");
    safeStorageSet(THREAD_STORAGE_KEY, this.threadId);
    this.appendMessage("system", `Created previewer editing task ${shortId(this.threadId)}. It edits the shared workspace; installation remains separately guarded.`);
  }

  async send() {
    const userText = this.elements.prompt.value.trim();
    if (!userText || !this.connected || this.busy || !this.threadId) return;
    const context = this.getContext?.() || {};
    this.appendMessage("user", userText);
    this.elements.prompt.value = "";
    this.busy = true;
    this.activeAssistantMessage = this.appendMessage("assistant", "");
    this.setStatus("Codex is inspecting and editing…");
    this.updateControls();
    try {
      const prompt = buildCodexTurnPrompt(userText, context);
      const response = await this.request("turn/start", {
        threadId: this.threadId,
        cwd: this.workspaceRoot,
        input: [{ type: "text", text: prompt }]
      });
      this.turnId = response.turn?.id || "";
    } catch (error) {
      this.busy = false;
      this.activeAssistantMessage.textContent = `Codex request failed: ${error.message}`;
      this.activeAssistantMessage = null;
      this.setStatus("Request failed", "bad");
      this.updateControls();
    }
  }

  updateSelectionContext(context) {
    if (!context?.selection) {
      this.elements.selection.textContent = context?.fileName ? `${context.fileName} · no widget selected` : "No widget selected";
      return;
    }
    const selected = context.selection;
    this.elements.selection.textContent = `${context.fileName} · ${selected.tag}${selected.id ? `#${selected.id}` : ""} · line ${selected.line ?? "?"} · ${selected.path}`;
  }

  handleMessage(event) {
    let message;
    try { message = JSON.parse(String(event.data)); } catch { return; }
    if (message.id != null) {
      const pending = this.pending.get(String(message.id));
      if (!pending) return;
      this.pending.delete(String(message.id));
      if (message.error) pending.reject(new Error(message.error.message || "Codex request failed."));
      else pending.resolve(message.result);
      return;
    }
    if (message.method === "item/agentMessage/delta" && message.params?.threadId === this.threadId) {
      if (!this.activeAssistantMessage) this.activeAssistantMessage = this.appendMessage("assistant", "");
      this.activeAssistantMessage.textContent += message.params.delta || "";
      this.elements.transcript.scrollTop = this.elements.transcript.scrollHeight;
      return;
    }
    if (message.method === "turn/completed" && message.params?.threadId === this.threadId) {
      this.busy = false;
      this.turnId = "";
      if (this.activeAssistantMessage && !this.activeAssistantMessage.textContent.trim()) {
        const finalMessage = findAgentMessage(message.params.turn?.items);
        this.activeAssistantMessage.textContent = finalMessage || "Codex completed the turn without a visible message.";
      }
      this.activeAssistantMessage = null;
      this.setStatus(`Ready · task ${shortId(this.threadId)}`, "ok");
      this.updateControls();
      void this.onTurnComplete?.();
      return;
    }
    if (message.method === "turn/failed" && message.params?.threadId === this.threadId) {
      const failure = message.params.error?.message || message.params.turn?.error?.message || "Codex could not complete the requested edit.";
      this.busy = false;
      this.turnId = "";
      if (!this.activeAssistantMessage) this.activeAssistantMessage = this.appendMessage("assistant", "");
      this.activeAssistantMessage.textContent = `Codex request failed: ${failure}`;
      this.activeAssistantMessage = null;
      this.setStatus("Request failed", "bad");
      this.updateControls();
    }
  }

  request(method, params) {
    if (!this.socket || this.socket.readyState !== WebSocket.OPEN) return Promise.reject(new Error("Codex is not connected."));
    const id = String(++this.requestId);
    this.socket.send(JSON.stringify({ method, id, params }));
    return new Promise((resolve, reject) => {
      const timeout = window.setTimeout(() => {
        this.pending.delete(id);
        reject(new Error(`${method} timed out.`));
      }, method === "turn/start" ? 30000 : 10000);
      this.pending.set(id, {
        resolve: (value) => { window.clearTimeout(timeout); resolve(value); },
        reject: (error) => { window.clearTimeout(timeout); reject(error); }
      });
    });
  }

  notify(method, params) {
    if (this.socket?.readyState === WebSocket.OPEN) this.socket.send(JSON.stringify({ method, params }));
  }

  appendMessage(role, text) {
    const message = document.createElement("p");
    message.className = `codex-message ${role}`;
    message.textContent = text;
    this.elements.transcript.append(message);
    this.elements.transcript.scrollTop = this.elements.transcript.scrollHeight;
    return message;
  }

  setStatus(message, state = "") {
    this.elements.status.textContent = message;
    this.elements.status.className = `codex-status ${state}`.trim();
  }

  updateControls() {
    this.elements.send.disabled = !this.connected || this.busy || !this.threadId || !this.elements.prompt.value.trim();
    this.elements.prompt.disabled = !this.connected || this.busy;
  }
}

function collectElements() {
  const byId = (id) => document.getElementById(id);
  return {
    status: byId("codexConnectionStatus"),
    transcript: byId("codexTranscript"),
    selection: byId("codexSelectionContext"),
    prompt: byId("codexPrompt"),
    send: byId("sendCodexPrompt")
  };
}

function findAgentMessage(items) {
  const agent = [...(items || [])].reverse().find((item) => item?.type === "agentMessage");
  return agent?.text || "";
}

function shortId(value) {
  const text = String(value || "");
  return text.length > 12 ? `${text.slice(0, 8)}…${text.slice(-4)}` : text;
}

function safeStorageGet(key) {
  try { return localStorage.getItem(key) || ""; } catch { return ""; }
}

function safeStorageSet(key, value) {
  try { localStorage.setItem(key, value); } catch { }
}

function safeStorageRemove(key) {
  try { localStorage.removeItem(key); } catch { }
}
